### ISSUE TITLE
Improvement requests

### ISSUE THREAD

**Issue by darby-rwc** [mcci-catena/rwc_nst_test#1]
Just want to give some feedback to enhance the NST operation from the implementation point of view.

**1. better to add "\n" in the definition of commands**
- it's general to add LF, CR, or both at the end of commands.

**2. processing of 't' cmd**
- after sending t, the tester expect 'ACK' from the Catena.
- then sending 'DONE' to the tester would be better to notify the transmission was done.

**3. processing of 'r' cmd**
- after sending r, the tester expect 'ACK' from the Catena.
- after completing transmission, the tester sends 'c', so the Catena stops the timer and replies with the count number (only number, e.g. 10)

**4. RX mode operation**
- the tester can stop it by sending 't' or 'c' 
- the timer can be interrupted by those cmds. 't' also initiates #2 above (maybe a timer is not necessary for this implementation).

**5. adding more commands**
- for flexibility, better to add more cmds for SF, # packets, Network, payloads, and so forth.

**Comment by terrillmoore** [comment]
To make it easier to track changes, I'll add sub-issues for each of these.
